# Generated by Django 5.2.1 on 2025-06-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('enrollment_date', models.DateField()),
                ('roll_no', models.PositiveBigIntegerField(unique=True)),
                ('address', models.TextField()),
            ],
        ),
    ]
