# Generated by Django 5.2.1 on 2025-06-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(default='None', max_length=50),
            preserve_default=False,
        ),
    ]
